# Generated by Django 3.0 on 2021-12-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('main_content', models.TextField()),
            ],
        ),
    ]
